#!bin/bash

echo " Instalar o dhcp..."
sudo yum update
sudo yum upgrade
sudo dnf install -y kea
~


#Interface em internal network
sudo nmcli connection modify ens33 ipv4.method manual ipv4.addresses 192.168.5.1/24
sudo nmcli connection modify ens33 +ipv4.addresses 192.168.5.1/24
sudo nmcli connection down ens33
sudo nmcli connection up ens33

#recolha de ips para utilizar 
echo "Introduz uma gama de ips que  pertençam a mesma subnet do servidor dhcp 192.168.5.1/24:"
echo "Atenção!!!! Não utilizar uma gama de IPS onde o ip do servidor ( 192.168.5.1/24) nem o ips do gateway (192.168.5.254) estejam presentes!!"
read -p " Ip de inicío :" ip_inicio
read -p " ip final:" ip_fim

#verificar o intervalo da gama de ips

subnet="^192\.168\.5\."
mask="255.255.255.0"
subrede="192.168.5.0"
ip_servidor="192.168.5.1"

if [[ $ip_inicio =~ $subnet ]] && [[ $ip_fim =~ $subnet ]] && [[ $ip_inicio != $ip_servidor ]] &&  [[ $ip_fim != $ip_servidor ]]; then
echo " Todos os IPS validados com sucesso!"
else
echo " ERRO : Os ips introduzidos estão errados ( fora da subnet) ou em conflito com o ip do servidor, fecha o programa e tenta denovo !"
exit 1
fi

# Ip default gateway
echo " Introduz o IP do default-gateway"
read -p "gateway:" ip_gateway

#verificar gateway
if [[ $ip_gateway =~ $subnet ]];then
echo " O default-gateway é válido!"
else
echo "ERRO :  O default-gateway está fora da subrede . Fecha o programa..."
exit 1
fi

#receber o dns
echo " Introduza o ip do DNS"
read -p " DNS:" dns

#backup
echo " Backup do arquivo de configuração DHCP-SERVER"
sudo cp /etc/dhcp/dhcp.conf /etc/dhcp/dhcp.conf.bak

{
"Dhcp4": {
    "interfaces-config": {
        "interfaces": [ "ens33" ]
    },
    "expired-leases-processing": {
        "reclaim-timer-wait-time": 10,
        "flush-reclaimed-timer-wait-time": 25,
        "hold-reclaimed-time": 3600,
        "max-reclaim-leases": 100,
        "max-reclaim-time": 250,
        "unwarned-reclaim-cycles": 5
    },
    "renew-timer": 900,
    "rebind-timer": 1800,
    "valid-lifetime": 3600,
    "option-data": [
        {
            "name": "domain-name-servers",
            "data": "192.168.5.0"
        },
        {
            "name": "domain-name",
            "data": "srv.world"
        },
        {
            "name": "domain-search",
            "data": "srv.world"
        }
    ],
    "subnet4": [
        {
            "id": 1,
            "subnet": "$subrede/24",
            "pools": [ { "pool": "$ip_inicio - $ip_fim" } ],
            "option-data": [
                {
                    "name": "routers",
                    "data": "10.0.0.1"
                }
            ]
        }
    ],
    "loggers": [
    {
        "name": "kea-dhcp4",
        "output-options": [
            {
                "output": "/var/log/kea/kea-dhcp4.log"
            }
        ],
        "severity": "INFO",
        "debuglevel": 0
    }
  ]
}
}
END

#Inicio DHCP
echo " A iniciar todas as configurações..."
sudo systemctl enable --now dhcpd.service
sudo systemctl start --now dhcpd.service
#ativar serviços firewall
echo " Configurar a firewall..."
sudo firewall-cmd --add-service=dhcp --permanent
sudo firewall-cmd --reload

#veriicar os status
echo " A verificar o status do DHCP..."
sudo systemctl status dhcpd.service

echo "PARABÉNS!!! Instalação realizada com sucesso."
